# for testing the service locally 

version: "3.9"
services:
  gateway:
    build: .
    container_name: sys-gateway-latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
